Added Czech and Swedish translations
Molkobain/itop-datacenter-view pull request #17
Opened 2021-11-26 10:23 UTC by xmstspider

Hi,

I translated your extension to Czech and Swedish.

2021-11-26 12:10 UTC, Molkobain commented
Hello @xmstspider thank you so much for your contribution! 🙌

I'll take a look this WE and integrate it.
Could you tell me if you would like to appear on the contributors list by your fullname or only your nickname? (If fullname, please provide it)

Cheers,
Guillaume

2021-11-26 15:20 UTC, xmstspider commented
Hello, happy to help :-)

You can use my full name: Zdenek Sedlak.

Thanks for the good work :-)

2021-11-28 16:55 UTC, Molkobain requested changes
A few changes are needed on some dictionaries headers before integration please.

2021-11-28 16:55 UTC, Molkobain commented on dist/molkobain-datacenter-view/molkobain-datacenter-view/cs.dict.molkobain-datacenter-view.php
> +Dict::Add('CZ CZ', 'Czech', 'Česky', array(
```suggestion
Dict::Add('CS CZ', 'Czech', 'Čeština', array(
```

In iTop existing czech dictionnaries are using another code / original language name like the suggestion I put.
I don't know which one is the correct one, but we need to keep it consistent with the other files for it to work well in all circumstances.

2021-11-28 16:55 UTC, Molkobain commented on dist/molkobain-datacenter-view/molkobain-datacenter-view/cs.dict.molkobain-datacenter-view.php
> +Dict::Add('CZ CZ', 'Czech', 'Česky', array(
```suggestion
Dict::Add('CS CZ', 'Czech', 'Čeština', array(
```

Same as the previous one.

2021-11-28 16:55 UTC, Molkobain commented on dist/molkobain-datacenter-view/molkobain-datacenter-view/sv.dict.molkobain-datacenter-view.php
> +Dict::Add('EN US', 'English', 'English', array(
```suggestion
Dict::Add('SV SV', 'Swedish', 'Svenska', array(
```

Typo, the old "english" header was kept.

2021-11-28 16:55 UTC, Molkobain commented on src/molkobain-datacenter-view/cs.dict.molkobain-datacenter-view.php
> +Dict::Add('CZ CZ', 'Czech', 'Česky', array(
```suggestion
Dict::Add('CS CZ', 'Czech', 'Čeština', array(
```

Same as for the previous czech file.

2021-11-28 16:55 UTC, Molkobain commented on src/molkobain-datacenter-view/cs.dict.molkobain-datacenter-view.php
> +Dict::Add('CZ CZ', 'Czech', 'Česky', array(
```suggestion
Dict::Add('CS CZ', 'Czech', 'Čeština', array(
```

Same as for the previous czech file.

2021-11-28 16:55 UTC, Molkobain commented on src/molkobain-datacenter-view/sv.dict.molkobain-datacenter-view.php
> +Dict::Add('EN US', 'English', 'English', array(
```suggestion
Dict::Add('SV SV', 'Swedish', 'Svenska', array(
```

2021-11-29 12:56 UTC, Molkobain approved these changes

2021-11-29 12:56 UTC, merged

2021-11-29 12:56 UTC, Molkobain commented
Thanks for the update !